### ISSUE TITLE
You also have a problem with parts flipped on layer in the PCB

### ISSUE THREAD

**Issue by ajawamnet** [antmicro/google-coral-baseboard#3]
Oh and in the Altium PCB file you have multiple parts that are shown as flipped on layer. In Altium 19 you'd never notice this (since they went f'ing brain dead and removed a lot of stuff we've come to depend on) BUT it is an issue if you're using AD17 or lower... this is bad mojo - ask any seasoned Altium user (me - I've done over 3,500 design with their tool since 1995).

Ya might want to fix this...

![flippedonlayer-badmojo](https://user-images.githubusercontent.com/25396864/65918718-5618fd80-e3a8-11e9-8382-8ac8f267998c.jpg)

**Comment by pkatarzynski** [comment]
Hi 

Thank you for your comment.
The design files were prepared in Altium Designer 14.1
We can see that some of the components on bottom layer have the 'flipped on layer' attribute set in the design however the pin arrangement on those footprints matches the physical arrangement on ICs. We will review the component library and unify this.

**Comment by ajawamnet** [comment]
The easiest thing to do is to open in AD19 and save out. This will clear the flipped on layer. You can then  use the Make PCBLib.
- Attached is the PCB with the power issue fix (your upload of 191001)   saved out of AD19.1.7 and re-saved as AD14.2 - along with the PCBLib saved out of AD14.2 with the report generated in AD17 (since PCBList in AD14 did not have a column for Flipped on Layer attribute) that shows all the "Flipped on layer" stoopid has been reset. 

[PCB-withpwrfix-ad19_to_ad14.zip](https://github.com/antmicro/google-coral-baseboard/files/3681559/PCB-withpwrfix-ad19_to_ad14.zip)


Also note I moved the "Cool ass" open source logo to clear the DRC from the keepout. 

BTW - the guy that runs the Free Software Foundation - the GNU thing - Richard Stallman. He HATES the term "Open Source". If you mention  "Open Source" to him more than a few times he'll stop talking/email chatting with you. 

The silly I've seen since I started back in the late 1970's ... all the cool man-bun java jockey maker crap - see my rant here: http://www.ajawamnet.com/ajawamnet/mama_i_wanna_be_a_maker.html

Good lord...

**Comment by ajawamnet** [comment]
updated PCB doc in AD14.2 format with adjustment for silly Open Source logo bottom soldermask 

[PCB-withpwrfix-ad19_to_ad14.zip](https://github.com/antmicro/google-coral-baseboard/files/3682505/PCB-withpwrfix-ad19_to_ad14.zip)

**Comment by pkatarzynski** [comment]
Thank you for your assistance. We have updated the PCB components with proper definitions of flipped-on-layer attribute.
