### ISSUE TITLE
Note that your one Hirose connector is off as compared to Googles' dev kit allegro file

### ISSUE THREAD

**Issue by ajawamnet** [antmicro/google-coral-baseboard#5]
Your JM3 and google's jm1312 ar nutz dead on as is jm0 and google's jm1310 - see screenshots of both overlayed on each other with the pads in draft mode...

But JM1 and googles j1311 are off about a half a mil... see attached
![jm3-j1312](https://user-images.githubusercontent.com/25396864/66333971-10a78380-e906-11e9-9e1b-758cca982f76.jpg)
![jm1-j1311](https://user-images.githubusercontent.com/25396864/66333972-10a78380-e906-11e9-979f-aa154eb6f5f5.jpg)
![ERROR-jm1-j1311](https://user-images.githubusercontent.com/25396864/66333973-10a78380-e906-11e9-843c-7c6e4b9a4c8f.jpg)
![jm0-j1310](https://user-images.githubusercontent.com/25396864/66333974-10a78380-e906-11e9-981b-30cda6497f2b.jpg)

**Comment by pkatarzynski** [comment]
We have updated positioning of Hirose connectors in rev. 1.3
