### ISSUE TITLE
Lack of SOM Mounting holes as per Google Datasheet

### ISSUE THREAD

**Issue by ajawamnet** [antmicro/google-coral-baseboard#6]
![noSOMmountingholes](https://user-images.githubusercontent.com/25396864/66335043-32096f00-e908-11e9-9c81-6ec82f48e7ab.jpg)

https://coral.withgoogle.com/docs/dev-board/datasheet/

**Comment by pkatarzynski** [comment]
Hi ajawamnet
We have dropped mounting holes on purpose in the first revision because of time constraints. Holes will be there in the next revision probably.
