### ISSUE TITLE
Your baseboard has components and copper in the area that Google mentions should be clear of these elements

### ISSUE THREAD

**Issue by ajawamnet** [antmicro/google-coral-baseboard#7]
See the attached:
![keepout_reqmnt_as_per_Google](https://user-images.githubusercontent.com/25396864/66340874-28860400-e914-11e9-95d5-55deb2733a15.jpg)

**Comment by pkatarzynski** [comment]
We have added clearance area in revision 1.3

**Comment by ajawamnet** [comment]
I hope that's enough - if you look at the Google ref baseboard, note there's nothing beyond the clearance area - the SOM is mounted at the edge of the PCB.  Even on your 1.3 rev, the WiFi will be radiating into your main power inductor ... not sure how that big honkin' piece of ferrite will affect the pattern and the loading/tuning of that PCB antenna they use. Be interesting to see how that works...
