### ISSUE TITLE
PCIE CLKREQ goes nowhere

### ISSUE THREAD

**Issue by ajawamnet** [antmicro/google-coral-baseboard#9]
the label PCIE2_nCLKREQ (I2C4_SDA) on JM1 pin 78 does not match the PCIE1_nCLKREQ  label on  M.2 interface pin 52

**Comment by pkatarzynski** [comment]
Hi 

Thank you for spotting this.
According to the latest datasheet of the Som (https://coral.withgoogle.com/docs/som/datasheet/#pcie)
both PCIe interfaces are used internally.
This information was not available when we designed the very first version of the baseboard. Hence we are going to drop the M.2 at this point.
